---
inherit_gem:
  rubocop-fnando: .rubocop.yml

AllCops:
  TargetRubyVersion: 2.5
  Exclude:
    - vendor/**/*

Style/AsciiComments:
  Enabled: false

Metrics/AbcSize:
  Enabled: false

Metrics/CyclomaticComplexity:
  Enabled: false

Metrics/PerceivedComplexity:
  Enabled: false

Style/Alias:
  Enabled: false

Layout/LineLength:
  Enabled: false

Style/IfUnlessModifier:
  Enabled: false

Metrics/MethodLength:
  Enabled: false

Metrics/BlockLength:
  Exclude:
    - bin/**/*
    - "*.gemspec"

Layout/EmptyLinesAroundAttributeAccessor:
  Enabled: false
