---
inherit_gem:
  rubocop-fnando: .rubocop.yml

AllCops:
  TargetRubyVersion: 2.5
  Exclude:
    - vendor/**/*

Style/AsciiComments:
  Enabled: false

Style/Alias:
  Enabled: false

Layout/LineLength:
  Enabled: false

Style/IfUnlessModifier:
  Enabled: false

Layout/EmptyLinesAroundAttributeAccessor:
  Enabled: false
